### ISSUE TITLE
Feature Request: Get request to trigger Kappagen effects

### ISSUE THREAD

**Issue by belthesar** [CBenni/KappaGen#4]
Hi there - 

One of the folks I work with has just started recently begun to leverage Kappagen, and absolutely loves it. However, one of the things we'd like to do is allow folks in chat be able to trigger an emotesplosion or other effects. The feature would obviously need to be limited, but that would be something well beyond the scope of Kappagen.  However, most chat bot frameworks are more than capable of handling this in a sane fashion.  What I would love to see is an endpoint that can be triggered with a simple HTTP GET request that has the ability to trigger the various functions of Kappagen based on parameters.  The bot can issue the GET request on behalf of the user, afford appropriate rate limiting, and trigger the effect.

**Comment by CBenni** [comment]
With the current, completely client-side approach, this is impossible. What you can do is have another bot use the !kappagen emotesplosiontest command, that works.
In KappaGen 3.0, which is in a planning stage, things like this will be easily possible.
Thanks for the feedback however, feel free to give your thoughts on this matter.

**Comment by belthesar** [comment]
Ahh, so the TMI session happens all inside of the client web page? That would explain that. Ideally, I'd like some back-channel method of issuing this command, whether it be a TMI session to a different channel, a whisper, or ideally a HTTP GET or RESTful API query of some sort, so that chat noise is minimized.  

If this requires running the instance of KappaGen outside of the cloud system, that's definitely doable (I'm not sure how much infrastructure you're interested in throwing at this little endeavor). I already host several assets, another small web app isn't gonna be a big deal. :-) 

Thanks for KappaGen by the way. This is a ridiculous and beautiful addition to Twitch.

**Comment by CBenni** [comment]
Well, for this to be done properly, youd need to move the cloud parts to your own provider, away from firebase. This is what I will be doing when I release KappaGen 3.0, which will probably be a barely noticeable transition for most. However, this will allow for things like web hooks, socket connections to KappaGen and all that goodie goodness - dont worry, its all planned out (and well, I already run something like a KappaGen server to account for the bad gamewisp API)
Thanks for your nice words!
